package administrador;

import conexion.conexion;
import static conexion.conexion.getConexion;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isaac_fa242tz
 */
public class registrarArreglos extends javax.swing.JInternalFrame {

    /**
     * Creates new form registrarArreglos
     */
    public registrarArreglos() {
        initComponents();
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombrearr = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcostoArr = new javax.swing.JTextField();
        calcCom = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtComision = new javax.swing.JTextField();
        registrararr = new javax.swing.JButton();
        tiempoElab = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArreglos = new javax.swing.JTable();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setClosable(true);
        setTitle("Registro de arreglos florales");

        jLabel1.setText("Nombre del arreglo");

        txtNombrearr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrearrActionPerformed(evt);
            }
        });

        jLabel2.setText("Tiempo de elaboración");

        jLabel3.setText("Costo del arreglo");

        calcCom.setText("Calcular");
        calcCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcComActionPerformed(evt);
            }
        });

        jLabel4.setText("Comisión");

        txtComision.setEditable(false);
        txtComision.setEnabled(false);

        registrararr.setText("Registrar arreglo");
        registrararr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrararrActionPerformed(evt);
            }
        });

        tiempoElab.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tiempoElab.setText("00:00:00");
        tiempoElab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tiempoElabKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(registrararr, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombrearr)
                            .addComponent(txtcostoArr)
                            .addComponent(txtComision)
                            .addComponent(tiempoElab, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcCom)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombrearr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempoElab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcostoArr, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calcCom, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registrararr)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tblArreglos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Arreglo", "Nombre", "Tiempo de elaboración", "Costo", "Comisión"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblArreglos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombrearrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrearrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrearrActionPerformed

    private void calcComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcComActionPerformed
        String costotxt;
        float costo,comision;
        
        comision=(float) 0.05;
        
        costotxt = txtcostoArr.getText();
        costo = Integer.parseInt(costotxt);
                
        costo = costo*comision;
        
        costotxt = Float.toString(costo);
        
        txtComision.setText(costotxt);
              
    }//GEN-LAST:event_calcComActionPerformed

    private void registrararrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrararrActionPerformed
                
    /* boton registrar pedidos */
        
        PreparedStatement ps = null;
        Connection con = getConexion(); /* conexion sql */

        String sql = "INSERT INTO catalogo (nombreArreglo,tiempoElaboracion,costoArreglo,comision) VALUES (?,?,?,?);"; /* consulta sql ingresa datos */

        try {
            ps = con.prepareStatement(sql); /* ingresa valor de los campos en Base de datos */
            ps.setString(1,txtNombrearr.getText());
            ps.setString(2,tiempoElab.getText());
            ps.setString(3,txtcostoArr.getText());
            ps.setString(4,txtComision.getText());

            int res=ps.executeUpdate(); /* ejecuta consulta */

            if(res>0){
                JOptionPane.showMessageDialog(null,"Pedido guardado con éxito"); /* si ejecuta la consulta devuelve mensaje */
                mostrar(); /* actualiza tabla y limpia campos */
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null,"No se han podido actualizar los datos");
            }
        } catch (SQLException ex) {
            Logger.getLogger(asignarPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_registrararrActionPerformed

    private void tiempoElabKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiempoElabKeyTyped
        if(tiempoElab.getText().length() >= 8){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_tiempoElabKeyTyped

    private void mostrar(){
        DefaultTableModel modelo = new DefaultTableModel();
        ResultSet rs = conexion.getTabla("SELECT * FROM CATALOGO");
        modelo.setColumnIdentifiers(new Object[]{"ID Arreglo","Nombre del arreglo","Tiempo de elaboración","Costo del arreglo","Comisión"});
        try{
            while(rs.next()){
            modelo.addRow(new Object[]{rs.getInt("idArreglo"),rs.getString("nombreArreglo"),rs.getTime("tiempoElaboracion"),rs.getDouble("costoArreglo"),rs.getDouble("comision")});
            }
        tblArreglos.setModel(modelo);
        }catch(Exception e){
            System.out.println(e);
        }
    }

    private void limpiar(){ /* metodo para limpiar los campos de texto y combo box */
        txtNombrearr.setText("");
        tiempoElab.setText("00:00:00");
        txtcostoArr.setText("");
        txtComision.setText("");
     }    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcCom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton registrararr;
    private javax.swing.JTable tblArreglos;
    private javax.swing.JTextField tiempoElab;
    private javax.swing.JTextField txtComision;
    private javax.swing.JTextField txtNombrearr;
    private javax.swing.JTextField txtcostoArr;
    // End of variables declaration//GEN-END:variables
}
